name: The Nemati Lab
description: Website for Nemati Lab at UC San Diego
url: NematiLab.info
permalink: :categories/:title
exclude: [vendor]
markdown: kramdown
host: localhost
sass:
    style: compressed
